### PR TITLE
screenshots for commons app- en IND

### PR DESCRIPTION
**Pull request by riya8866**

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
You don't have to close this pull request, just push new commits and they will be added to it automatically :-)

**Comment by riya8866** [comment]
by mistake i have closed it and now i m neither able to reopen it nor able to make a new one as its showing that the uploads are disabled.

**Comment by riya8866** [comment]
please tell me how can i fix it.

**Comment by nicolas-raoul** [comment]
It looks like you deleted your repository. Please clone again.

**Comment by riya8866** [comment]
When I am selecting the folder from my local system, it is automatically uploading the screenshots seperately instead of uploading them together in a folder.

**Pull request closed without merging**
